name: NextJS Build Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setting Up Node.JS
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: '20'
          # cache: 'npm'
          # # cache-dependency-path: './node_modules'
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies (it looks for package.json and installs from there)
        run: npm install
      
      - name: Build
        run : npm install build
      
      - name: Verfiy the build/output folder
        run : ls -l out
      
      - name: Upload Artifacts
        uses : actions/upload-artifact@v4.3.3
        with:
          name: AlphaApp_Build_Files
          path: out

      - name: Installing Neflify CLI
        run : npm install -g netlify-cli
      
      - name: Deploy to netlify-cli
        run : |
          neflify deploy --prod \
            --dir=out \
            --site ${{ secrets.NETLIFY_ALPHAAPP_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_ALPHAAPP_TOKEN }}


